

INSERT INTO wf_flow_define VALUES ('000068', '0', '请假流程', 'R', null, 'A', 'xxxx', null, '', 'N', 'bx_flow', null, null);
INSERT INTO wf_flow_define VALUES ('129', '0', null, 'R', null, 'A', null, null, null, null, null, null, null);
INSERT INTO wf_flow_define VALUES ('130', '0', null, 'R', null, 'A', null, null, null, null, null, null, null);


INSERT INTO wf_flow_instance VALUES ('340', '12', '000070', null, '341',sysdate, 'F', null, null, 'u0000000', null, 'N', 'N', '0', '0', null, 'u0000000');
INSERT INTO wf_flow_instance VALUES ('341', '1', '171', '报销流程02实例001', '001', sysdate, 'F', null, null, 'u0000000',null, 'N', 'N', '0', '0', '', 'u0000000');
INSERT INTO wf_flow_instance VALUES ('342', '1', '171', '报销流程02实例002', '002', sysdate, 'F', null, null, null, null, 'N', 'N', '0', '0', '', 'u0000000');

INSERT INTO wf_flow_variable VALUES ('340', 'A', 'auditorCount', '1', 'S');
INSERT INTO wf_flow_variable VALUES ('340', 'A', 'currentPhase', '1', 'S');
INSERT INTO wf_flow_variable VALUES ('340', 'A', 'maxPhase', '2', 'S');

INSERT INTO wf_inst_attention VALUES ('1', '2', null, '2', null);
INSERT INTO wf_inst_attention VALUES ('1', 'u0000001', null, 'u0000000', null);

INSERT INTO wf_node VALUES ('1', '8', '1', 'A', '开始', null, 'TEST', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('2', '8', '1', 'F', '结束', null, 'TEST', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('3', '8', '1', 'B', '过程', 'A', 'TEST', null, 'null', '', '', '', null, 'bj', 'null', 'P', '', null, null, null, null, null, 'F', 'I', null, '0', '', '', 'R', '', 'F', null, '', null);
INSERT INTO wf_node VALUES ('4', '8', '1', 'C', '过程', 'A', 'TEST', null, 'null', '', '', '', null, 'xz', 'GM', 'P', '', null, null, null, null, null, 'F', 'I', null, '0', '', '', 'R', '', 'F', null, '', null);
INSERT INTO wf_node VALUES ('16', '000057', '1', 'A', '开始', null, null, null, null, null, null, null, null, 'null', 'null', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('17', '000057', '1', 'F', '结束', null, null, null, null, null, null, null, null, 'null', 'null', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('18', '000057', '1', 'B', '过程', 'A', null, null, '20000011', '', null, null, null, 'bj', 'null', 'P', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('21', '000057', '2', 'A', '开始', null, null, null, null, null, null, null, null, 'null', 'null', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('22', '000057', '2', 'F', '结束', null, null, null, null, null, null, null, null, 'null', 'null', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('23', '000057', '2', 'B', '过程', 'A', null, null, '20000011', '', null, null, null, 'bj', 'null', 'P', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('536', '000070', '6', 'A', '开始', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('537', '000070', '6', 'F', '结束', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('538', '000070', '6', 'R', '分支节点1', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('539', '000070', '6', 'C', '单人审核', 'A', null, null, '20000011', 'SetNextAuditorsBean', null, null, null, 'bj', 'auditor', 'P', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('540', '000070', '6', 'C', '多人审核', 'A', null, null, '20000011', 'VoteAndSetAuditorsBean', null, null, null, 'bj', 'auditor', 'P', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('541', '000070', '6', 'R', '多实例分支', null, null, null, null, null, null, null, 'G', 'bj', 'auditor', '', '', 'U', 'null', null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('542', '000070', '6', 'R', '多实例汇聚', null, null, null, null, 'JoinEvent', null, null, 'E', null, null, null, null, null, null, 'E', '', null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('543', '000070', '6', 'R', '分支节点2', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('544', '000070', '6', 'R', '分支节点3', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('545', '000070', '6', 'B', '申请', 'A', null, null, '20000011', '', null, null, null, 'bj', 'jbr', 'P', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('558', '000070', '7', 'A', '开始', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('559', '000070', '7', 'F', '结束', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('560', '000070', '7', 'R', '分支节点1', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('561', '000070', '7', 'C', '单人审核', 'A', null, null, '20000011', 'SetNextAuditorsBean', null, null, null, 'bj', 'auditor', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('562', '000070', '7', 'C', '多人审核', 'A', null, null, '20000011', 'VoteAndSetAuditorsBean', null, null, null, 'bj', 'auditor', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('563', '000070', '7', 'R', '多实例分支', null, null, null, null, null, null, null, 'G', 'en', 'auditor', '', 'auditor', 'U', 'null', null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('564', '000070', '7', 'R', '多实例汇聚', null, null, null, null, 'JoinEvent', null, null, 'E', null, null, null, null, null, null, 'A', '', null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('565', '000070', '7', 'R', '分支节点2', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('566', '000070', '7', 'R', '分支节点3', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('567', '000070', '7', 'B', '申请', 'A', null, null, '20000011', '', null, null, null, 'bj', 'jbr', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('652', '000070', '8', 'A', '开始', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('653', '000070', '8', 'F', '结束', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('654', '000070', '8', 'R', '分支节点1', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('655', '000070', '8', 'C', '单人审核', 'A', null, null, '20000011', '', null, null, null, 'bj', 'auditor', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('656', '000070', '8', 'C', '多人审核', 'A', null, null, '20000011', 'VoteAndSetAuditorsBean', null, null, null, 'bj', 'auditor', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('657', '000070', '8', 'R', '多实例分支', null, null, null, null, null, null, null, 'G', 'bj', 'auditor', '', '', 'U', 'null', null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('658', '000070', '8', 'R', '多实例汇聚', null, null, null, null, '', null, null, 'E', null, null, null, null, null, null, 'A', '', null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('659', '000070', '8', 'R', '分支节点2', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('660', '000070', '8', 'R', '分支节点3', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('661', '000070', '8', 'B', '申请', 'A', null, null, '20000011', '', null, null, null, 'bj', 'jbr', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('662', '000070', '8', 'C', '设置下一步审核人', 'D', null, null, '20000011', 'SetNextAuditorsBean', null, null, null, '', 'null', 'P', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('676', '000070', '9', 'A', '开始', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('677', '000070', '9', 'F', '结束', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('678', '000070', '9', 'R', '分支节点1', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('679', '000070', '9', 'C', '单人审核', 'A', null, null, '20000011', '', null, null, null, 'bj', 'auditor', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('680', '000070', '9', 'C', '多人审核', 'A', null, null, '20000011', 'VoteAndSetAuditorsBean', null, null, null, 'bj', 'auditor', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('681', '000070', '9', 'R', '多实例分支', null, null, null, null, null, null, null, 'G', 'bj', 'auditor', '', '', 'U', 'null', null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('682', '000070', '9', 'R', '多实例汇聚', null, null, null, null, '', null, null, 'E', null, null, null, null, null, null, 'A', '', null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('683', '000070', '9', 'R', '分支节点2', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('684', '000070', '9', 'R', '分支节点3', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('685', '000070', '9', 'B', '申请', 'A', null, null, '20000011', '', null, null, null, 'bj', 'jbr', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('686', '000070', '9', 'C', '设置下一步审核人', 'D', null, null, '20000011', 'SetNextAuditorsBean', null, null, null, '', 'null', 'P', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('724', '000070', '10', 'A', '开始', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('725', '000070', '10', 'F', '结束', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('726', '000070', '10', 'R', '分支节点1', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('727', '000070', '10', 'C', '单人审核', 'A', null, null, '20000011', '', null, null, null, 'bj', 'auditor', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('728', '000070', '10', 'C', '多人审核', 'A', null, null, '20000011', 'VoteAndSetAuditorsBean', null, null, null, 'bj', 'auditor', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('729', '000070', '10', 'R', '多实例分支', null, null, null, null, null, null, null, 'G', 'bj', 'auditor', '', '', 'U', 'null', null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('730', '000070', '10', 'R', '多实例汇聚', null, null, null, null, '', null, null, 'E', null, null, null, null, null, null, 'A', '', null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('731', '000070', '10', 'R', '分支节点2', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('732', '000070', '10', 'R', '分支节点3', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('733', '000070', '10', 'B', '申请', 'A', null, null, '20000011', '', null, null, null, 'bj', 'jbr', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('734', '000070', '10', 'C', '过程', 'D', null, null, '20000011', 'SetNextAuditorsBean', null, null, null, '', 'null', 'P', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('772', '000070', '11', 'A', '开始', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('773', '000070', '11', 'F', '结束', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('774', '000070', '11', 'R', '分支节点1', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('775', '000070', '11', 'C', '单人审核', 'A', null, null, '20000011', '', null, null, null, 'bj', 'auditor', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('776', '000070', '11', 'C', '多人审核', 'A', null, null, '20000011', 'VoteAndSetAuditorsBean', null, null, null, 'bj', 'auditor', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('777', '000070', '11', 'R', '多实例分支', null, null, null, null, null, null, null, 'G', 'bj', 'auditor', '', '', 'U', 'null', null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('778', '000070', '11', 'R', '多实例汇聚', null, null, null, null, '', null, null, 'E', null, null, null, null, null, null, 'A', '', null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('779', '000070', '11', 'R', '分支节点2', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('780', '000070', '11', 'R', '分支节点3', null, null, null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('781', '000070', '11', 'B', '申请', 'A', null, null, '20000011', '', null, null, null, 'bj', 'jbr', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('782', '000070', '11', 'C', '过程', 'D', null, null, '20000011', 'SetNextAuditorsBean', null, null, null, '', 'null', 'P', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('796', '000070', '12', 'A', '开始', null, 'TEST', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('797', '000070', '12', 'F', '结束', null, 'TEST', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('798', '000070', '12', 'R', '分支节点1', null, 'TEST', null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('799', '000070', '12', 'C', '单人审核', 'A', 'TEST', null, '20000011', '', null, null, null, 'bj', 'auditor', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('800', '000070', '12', 'C', '多人审核', 'A', 'TEST', null, '20000011', 'VoteAndSetAuditorsBean', null, null, null, 'bj', 'auditor', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('801', '000070', '12', 'R', '多实例分支', null, 'TEST', null, null, null, null, null, 'G', 'bj', 'auditor', '', '', 'U', 'null', null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('802', '000070', '12', 'R', '多实例汇聚', null, 'TEST', null, null, '', null, null, 'E', null, null, null, null, null, null, 'A', '', null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('803', '000070', '12', 'R', '分支节点2', null, 'TEST', null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('804', '000070', '12', 'R', '分支节点3', null, 'TEST', null, null, null, null, null, 'D', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'F', null, null, null);
INSERT INTO wf_node VALUES ('805', '000070', '12', 'B', '申请', 'A', 'TEST', null, '20000011', '', null, null, null, 'bj', 'jbr', '', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('806', '000070', '12', 'C', '过程', 'D', 'TEST', null, '20000011', 'SetNextAuditorsBean', null, null, null, '', 'null', 'P', '', null, null, null, null, null, 'F', 'I', null, '0', '', null, 'R', '', 'F', null, null, null);
INSERT INTO wf_node VALUES ('837', '171', '1', 'A', '开始', null, 'TEST', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('838', '171', '1', 'F', '结束', null, 'TEST', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO wf_node VALUES ('839', '171', '1', 'B', '过程', 'A', 'TEST', null, '20000011', '', '', '', null, 'bj', 'jbr', 'P', '', null, null, null, null, null, 'F', 'I', null, '0', '', '', 'R', '', 'F', null, '', null);
INSERT INTO wf_node VALUES ('840', '171', '1', 'C', '过程', 'A', 'TEST', null, '20000011', '', '', '', null, 'bj', 'auditor', 'P', '', null, null, null, null, null, 'F', 'I', null, '0', '', '', 'R', '', 'F', null, '', null);

INSERT INTO wf_node_instance VALUES ('938', '340', '805', null, null, 'F', '0', '0', null, 'C', null, null, null, 'bj', 'jbr', 'u0000000', null, null, 'S', 'T', null, 'u0000000', null, null);
INSERT INTO wf_node_instance VALUES ('939', '340', '799', null, null, 'F', '0', '0', '938', 'N', null, null, null, 'bj', 'auditor', 'u0000002', null, null, 'S', 'T', null, 'u0000000', null, '813,807');
INSERT INTO wf_node_instance VALUES ('940', '341', '839', null, null, 'F', '0', '0', null, 'F', null, '', null, 'bj', 'jbr', 'u0000000', null, null, 'S', 'T', null, 'u0000000', null, null);
INSERT INTO wf_node_instance VALUES ('941', '341', '840',null, null, 'F', '0', '0', '839', 'N', null, '', null, 'bj', 'auditor', 'u0000000', null, null, 'S', 'T', null, 'u0000000', null, '842');
INSERT INTO wf_node_instance VALUES ('942', '342', '839', null, null, 'F', '0', '0', null, 'N', null, '', null, 'bj', 'jbr', 'u0000000', null, null, 'S', 'T', null, 'u0000000', null, null);

INSERT INTO wf_organize VALUES ('5', '1', '1', null, '1',null);

INSERT INTO wf_role_relegate VALUES ('1', 'u0000000', 'u0000001', 'T', null, sysdate, null, null, null, null, null, null);
INSERT INTO wf_role_relegate VALUES ('2', 'u0000001', 'u0000000', 'T', null, sysdate, null, null, null, null, null, null);

INSERT INTO wf_team VALUES ('340', 'auditor', 'u0000002', null, null, null);

INSERT INTO wf_transition VALUES ('5', '1', '8', null, '流程step', '1', '3', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('6', '1', '8', null, '流程step', '3', '4', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('7', '1', '8', null, '流程step', '4', '2', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('19', '1', '000057', null, '流程step', '16', '18', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('20', '1', '000057', null, '流程step', '18', '17', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('24', '2', '000057', null, '流程step', '21', '23', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('25', '2', '000057', null, '流程step', '23', '22', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('439', '1', '000070', null, '', '432', '433', 'count(auditor)=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('440', '1', '000070', null, '', '432', '435', 'count(auditor)>1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('441', '1', '000070', null, '', '435', '434', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('442', '1', '000070', null, '', '434', '436', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('443', '1', '000070', null, '', '436', '437', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('444', '1', '000070', null, '审核不通过', '437', '431', 'pass=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('445', '1', '000070', null, '审核通过', '437', '438', 'pass=0', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('446', '1', '000070', null, '没有其他审批节点', '438', '431', 'currentPhase=maxPhase', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('447', '1', '000070', null, '流程step', '433', '437', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('448', '1', '000070', null, '流程step', '438', '432', 'currentPhase=maxPhase', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('449', '1', '000070', null, '流程step', '430', '432', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('459', '2', '000070', null, '', '452', '453', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('460', '2', '000070', null, '', '452', '455', 'count(auditor)>1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('461', '2', '000070', null, '', '455', '454', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('462', '2', '000070', null, '', '454', '456', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('463', '2', '000070', null, '', '456', '457', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('464', '2', '000070', null, '审核不通过', '457', '451', 'pass=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('465', '2', '000070', null, '审核通过', '457', '458', 'pass=0', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('466', '2', '000070', null, '没有其他审批节点', '458', '451', 'currentPhase=maxPhase', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('467', '2', '000070', null, '流程step', '453', '457', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('468', '2', '000070', null, '流程step', '458', '452', 'currentPhase=maxPhase', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('469', '2', '000070', null, '流程step', '450', '452', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('480', '3', '000070', null, '', '472', '473', 'count(auditor)=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('481', '3', '000070', null, '', '472', '475', 'count(auditor)>1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('482', '3', '000070', null, '', '475', '474', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('483', '3', '000070', null, '', '474', '476', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('484', '3', '000070', null, '', '476', '477', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('485', '3', '000070', null, '审核不通过', '477', '471', 'pass=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('486', '3', '000070', null, '审核通过', '477', '478', 'pass=0', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('487', '3', '000070', null, '没有其他审批节点', '478', '471', 'currentPhase=maxPhase', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('488', '3', '000070', null, '流程step', '473', '477', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('489', '3', '000070', null, '流程step', '478', '472', 'currentPhase=maxPhase', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('490', '3', '000070', null, '流程step', '470', '479', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('491', '3', '000070', null, '流程step', '479', '472', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('502', '4', '000070', null, '', '494', '495', 'auditorCount=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('503', '4', '000070', null, '', '494', '497', 'auditorCount>1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('504', '4', '000070', null, '', '497', '496', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('505', '4', '000070', null, '', '496', '498', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('506', '4', '000070', null, '', '498', '499', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('507', '4', '000070', null, '审核不通过', '499', '493', 'pass=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('508', '4', '000070', null, '审核通过', '499', '500', 'pass=0', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('509', '4', '000070', null, '没有其他审批节点', '500', '493', 'currentPhase=maxPhase', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('510', '4', '000070', null, '流程step', '495', '499', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('511', '4', '000070', null, '流程step', '500', '494', 'currentPhase=maxPhase', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('512', '4', '000070', null, '流程step', '492', '501', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('513', '4', '000070', null, '流程step', '501', '494', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('524', '5', '000070', null, '', '516', '517', 'auditorCount=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('525', '5', '000070', null, '', '516', '519', 'auditorCount>1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('526', '5', '000070', null, '', '519', '518', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('527', '5', '000070', null, '', '518', '520', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('528', '5', '000070', null, '', '520', '521', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('529', '5', '000070', null, '审核不通过', '521', '515', 'pass=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('530', '5', '000070', null, '审核通过', '521', '522', 'pass=0', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('531', '5', '000070', null, '没有其他审批节点', '522', '515', 'currentPhase=maxPhase', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('532', '5', '000070', null, '流程step', '517', '521', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('533', '5', '000070', null, '流程step', '522', '516', 'currentPhase=maxPhase', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('534', '5', '000070', null, '流程step', '514', '523', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('535', '5', '000070', null, '流程step', '523', '516', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('546', '6', '000070', null, '', '538', '539', 'auditorCount=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('547', '6', '000070', null, '', '538', '541', 'auditorCount>1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('548', '6', '000070', null, '', '541', '540', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('549', '6', '000070', null, '', '540', '542', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('550', '6', '000070', null, '', '542', '543', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('551', '6', '000070', null, '审核不通过', '543', '537', 'pass=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('552', '6', '000070', null, '审核通过', '543', '544', 'pass=0', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('553', '6', '000070', null, '没有其他审批节点', '544', '537', 'currentPhase=maxPhase', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('554', '6', '000070', null, '流程step', '539', '543', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('555', '6', '000070', null, '流程step', '544', '538', 'currentPhase=maxPhase', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('556', '6', '000070', null, '流程step', '536', '545', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('557', '6', '000070', null, '流程step', '545', '538', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('568', '7', '000070', null, '', '560', '561', 'auditorCount=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('569', '7', '000070', null, '', '560', '563', 'auditorCount>1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('570', '7', '000070', null, '', '563', '562', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('571', '7', '000070', null, '', '562', '564', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('572', '7', '000070', null, '', '564', '565', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('573', '7', '000070', null, '审核不通过', '565', '559', 'pass=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('574', '7', '000070', null, '审核通过', '565', '566', 'pass=0', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('575', '7', '000070', null, '没有其他审批节点', '566', '559', 'currentPhase=maxPhase+1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('576', '7', '000070', null, '流程step', '561', '565', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('577', '7', '000070', null, '流程step', '566', '560', 'currentPhase<maxPhase+1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('578', '7', '000070', null, '流程step', '558', '567', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('579', '7', '000070', null, '流程step', '567', '560', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('663', '8', '000070', null, '单人审核', '654', '655', 'auditorCount=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('664', '8', '000070', null, '多人审核', '654', '657', 'auditorCount>1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('665', '8', '000070', null, '多实例分支', '657', '656', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('666', '8', '000070', null, '多实例汇聚', '656', '658', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('667', '8', '000070', null, '审核不通过', '659', '653', 'pass=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('668', '8', '000070', null, '审核通过', '659', '660', 'pass=0', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('669', '8', '000070', null, '没有其他审批节点', '660', '653', 'currentPhase=maxPhase+1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('670', '8', '000070', null, '发起申请', '652', '661', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('671', '8', '000070', null, '提交申请', '661', '654', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('672', '8', '000070', null, '继续审核', '660', '654', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('673', '8', '000070', null, '设置下一步审核人', '658', '662', 'complete=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('674', '8', '000070', null, '流程step', '662', '659', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('675', '8', '000070', null, '设置下一步审核人', '655', '662', 'complete=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('687', '9', '000070', null, '单人审核', '678', '679', 'auditorCount=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('688', '9', '000070', null, '多人审核', '678', '681', 'auditorCount>1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('689', '9', '000070', null, '多实例分支', '681', '680', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('690', '9', '000070', null, '多实例汇聚', '680', '682', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('691', '9', '000070', null, '审核不通过', '683', '677', 'pass=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('692', '9', '000070', null, '审核通过', '683', '684', 'pass=0', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('693', '9', '000070', null, '没有其他审批节点', '684', '677', 'currentPhase=maxPhase+1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('694', '9', '000070', null, '发起申请', '676', '685', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('695', '9', '000070', null, '提交申请', '685', '678', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('696', '9', '000070', null, '继续审核', '684', '678', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('697', '9', '000070', null, '设置下一步审核人', '682', '686', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('698', '9', '000070', null, '流程step', '686', '683', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('699', '9', '000070', null, '设置下一步审核人', '679', '686', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('735', '10', '000070', null, '单人审核', '726', '727', 'auditorCount=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('736', '10', '000070', null, '多人审核', '726', '729', 'auditorCount>1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('737', '10', '000070', null, '多实例分支', '729', '728', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('738', '10', '000070', null, '多实例汇聚', '728', '730', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('739', '10', '000070', null, '没有其他审批节点', '732', '725', 'currentPhase=maxPhase+1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('740', '10', '000070', null, '发起申请', '724', '733', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('741', '10', '000070', null, '提交申请', '733', '726', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('742', '10', '000070', null, '继续审核', '732', '726', 'currentPhase<maxPhase+1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('743', '10', '000070', null, '流程step', '727', '731', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('744', '10', '000070', null, '流程step', '730', '731', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('745', '10', '000070', null, '不通过', '731', '725', 'pass=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('746', '10', '000070', null, '通过', '731', '734', 'pass=0', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('747', '10', '000070', null, '流程step', '734', '732', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('783', '11', '000070', null, '单人审核', '774', '775', 'auditorCount=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('784', '11', '000070', null, '多人审核', '774', '777', 'auditorCount>1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('785', '11', '000070', null, '多实例分支', '777', '776', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('786', '11', '000070', null, '多实例汇聚', '776', '778', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('787', '11', '000070', null, '没有其他审批节点', '780', '773', 'currentPhase=maxPhase+1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('788', '11', '000070', null, '发起申请', '772', '781', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('789', '11', '000070', null, '提交申请', '781', '774', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('790', '11', '000070', null, '继续审核', '780', '774', 'currentPhase<maxPhase+1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('791', '11', '000070', null, '不通过', '779', '773', 'pass=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('792', '11', '000070', null, '流程step', '775', '782', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('793', '11', '000070', null, '流程step', '782', '779', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('794', '11', '000070', null, '流程step', '778', '782', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('795', '11', '000070', null, '通过', '779', '780', 'pass=0', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('807', '12', '000070', null, '单人审核', '798', '799', 'auditorCount=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('808', '12', '000070', null, '多人审核', '798', '801', 'auditorCount>1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('809', '12', '000070', null, '多实例分支', '801', '800', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('810', '12', '000070', null, '多实例汇聚', '800', '802', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('811', '12', '000070', null, '没有其他审批节点', '804', '797', 'currentPhase=maxPhase+1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('812', '12', '000070', null, '发起申请', '796', '805', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('813', '12', '000070', null, '提交申请', '805', '798', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('814', '12', '000070', null, '继续审核', '804', '798', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('815', '12', '000070', null, '不通过', '803', '797', 'pass=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('816', '12', '000070', null, '流程step', '799', '806', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('817', '12', '000070', null, '流程step', '806', '803', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('818', '12', '000070', null, '流程step', '802', '806', '1=1', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('819', '12', '000070', null, '通过', '803', '804', 'pass=0', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('841', '1', '171', null, '流程step', '837', '839', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('842', '1', '171', null, '流程step', '839', '840', '', '', 'F', 'I', null, null, null, 'F');
INSERT INTO wf_transition VALUES ('843', '1', '171', null, '流程step', '840', '838', '', '', 'F', 'I', null, null, null, 'F');

commit;